tools: gcc-arm-none-eabi-6-2017-q1-update STM32Cube_FW_F0_V1.8.0

gcc-arm-none-eabi-6-2017-q1-update: gcc-arm-none-eabi-6-2017-q1-update-linux.tar.bz2
	tar xjf $<

STM32Cube_FW_F0_V1.8.0: en.stm32cubef0.zip
	unzip -q -DD $<
