tools: gcc-arm-none-eabi-6-2017-q2-update STM32Cube_FW_F0_V1.9.0

# https://developer.arm.com/open-source/gnu-toolchain/gnu-rm
gcc-arm-none-eabi-6-2017-q2-update: gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
	tar xjmf $<

# http://www.st.com/en/embedded-software/stm32cubef0.html
STM32Cube_FW_F0_V1.9.0: en.stm32cubef0.zip
	unzip -q -DD $<
