gcc-arm-none-eabi-5_4-2016q3: gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2
	@tar xjf $<

gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2:
	@wget https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q3-update/+download/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2
